name: tic_tac_toe_eng
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  tic_tac_toe_engine:
    path: packages/tic_tac_toe_engine/
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - 'assets/'